CREATE TABLE `dspotter_order_history` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `ORDER_ID` INT(11) NOT NULL,
        `CID` VARCHAR(255),
        `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(ID)
);

CREATE TABLE `dspotter_settings` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `PLUGIN_ENABLED` tinyint (1) NOT NULL,
        `HASH` VARCHAR(255),
        `ORDER_CANCEL` VARCHAR (10),
        `SITE_NAME` VARCHAR(255),
        `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(ID)
);